### ISSUE TITLE
keyError

### ISSUE THREAD

**Issue by rstatistics** [SingleronBio/SCOPE-tools#18]
我使用最新版scope-tools-0.2.1，使用默认的参数，报错了。然后发现想使用上一个版本却不能安装。
conda install -c singleronbio scope-tools=0.2.0 
找不到，希望作者解决一下，谢谢~

**Comment by luyang93** [comment]
能否贴一下报错信息呢?

**Comment by rstatistics** [comment]
[Log.txt](https://github.com/SingleronBio/SCOPE-tools/files/4813363/Log.txt)
麻烦您帮我看看啊，跑的就是你们公司产的数据。谢谢

**Comment by luyang93** [comment]
磁珠数据还是微珠数据呢

**Comment by rstatistics** [comment]
看不懂你说的，我取几个headerID你瞧瞧？
每个barcode都这么长，AAACATCGAAACATCGAACGTGAT，公司给的是个xls文件。

**Comment by luyang93** [comment]
发几个R1序列呢？

**Comment by rstatistics** [comment]
@A00473:28:HNKM2DSXX:3:1101:1579:1000 1:N:0:TCGAGCGT
AAGGTACAATCCACGTGCTTGAGACTGTAGCCTCAGCATGCGGCTACGAACGTGATCCTATTCCGTTTTTTTTTTTTTTTTTTTTCTTAACTTCTTGCTTAATTGAATTTTTATGGCTAATCACAAATAATGCCAAAAAAGGAGTTTTTA
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF::FFFFFFFFFFFFFFFFFFFFFFF,F,FF,F,FF,F:,:FFF,,F,:,F,FF:FF:FFFF,F,F,,F,F:,FFF:,:FFF,F:,FFF:F,
@A00473:28:HNKM2DSXX:3:1101:1723:1000 1:N:0:TCGAGCGT
CCGTGAGAATCCACGTGCTTGAGAGTCGTAGATCAGCATGCGGCTACGAACGTGATCGGGTGGCATTTTTTTTTTTTTTTTTTCTGCAATTTCTACTTGTTCTTTTTATAAAATAAAACTAGTATGCATTTCAACAACCTGGCTTTATAAT
+
FFFFFFFF:FFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFF,FFFFFFFFFFFFFFFFF:F::::,F:F:FFF::FFFFF:FF,FFFFF,:FFF:FF:FFF:FF:FFFFF,,,:::FFFFF,,FFFF
@A00473:28:HNKM2DSXX:3:1101:1814:1000 1:N:0:TCGAGCGT
ACGTATCAATCCACGTGCTTGAGAGAATCTGATCAGCATGCGGCTACGAACGTTATCCGGAGATATTTTTTTTTTTTTTTTTTGGGTGGGTGTGGGTATAATACTAAGTTGAGATGATATCATTTACGGGGGAAGGCGCTTTGTGAAGT

**Comment by rstatistics** [comment]
等解决了，把这个issue删掉，太乱啦

**Comment by rstatistics** [comment]
你要不给我个邮箱，我的邮箱是：admin@ncrna.net，我把小的数据发您跑跑，看能跑通吗，估计就几分钟就跑完了，总共12Mb左右的文件。

**Comment by luyang93** [comment]
luyangshare93@gmail.com
我第一个关注点是，featurecount居然两分钟跑完了，我在想数据会不会不对，过滤后太少了。
issue删不掉，只能close

**Comment by luyang93** [comment]
fix in #19 .
